version: '3.8'

services:
  app:
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    
  db:
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker 